// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

import type { UserDO } from './src/index';

interface Env {
  WEBHOOK_IDEMPOTENCY: KVNamespace;
  ARTICLE_CONTENT: R2Bucket;
  ENVIRONMENT: 'development' | 'staging' | 'production';
  USER_DO: DurableObjectNamespace<UserDO>;
}

// Extend ProvidedEnv for vitest-pool-workers
declare module 'cloudflare:test' {
  interface ProvidedEnv extends Env {
    __brand?: never;
  }
}
