// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
  WEBHOOK_IDEMPOTENCY: KVNamespace;
  ARTICLE_CONTENT: R2Bucket;
  ENVIRONMENT: 'development' | 'staging' | 'production';
  // eslint-disable-next-line @typescript-eslint/consistent-type-imports
  USER_DO: DurableObjectNamespace<import('./src/index').UserDO>;
}

// Extend ProvidedEnv for vitest-pool-workers
declare module 'cloudflare:test' {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface ProvidedEnv extends Env {}
}
