import weeklyRecaps from './api-v1/weekly-recaps';
import publicationDelivery from './api-v1/publication-delivery';
import { Hono } from 'hono';
import publications from './api-v1/publications';
import type { Env } from '../types';
import openApiSpec from './api-v1.openapi.json';
import subscriptions from './api-v1/subscriptions';
import sync from './api-v1/sync';
import library from './api-v1/library';
import podcasts from './api-v1/podcasts';
import creators from './api-v1/creators';
import today from './api-v1/today';
import editorialExperiments from './api-v1/editorial-experiments';
import editorial from './api-v1/editorial';

const apiV1Routes = new Hono<Env>();
apiV1Routes.get('/openapi.json', (c) => c.json(openApiSpec));
apiV1Routes.route('/', publications);
apiV1Routes.route('/', weeklyRecaps);
apiV1Routes.route('/', publicationDelivery);
apiV1Routes.route('/', subscriptions);
apiV1Routes.route('/', sync);
apiV1Routes.route('/', library);
apiV1Routes.route('/', podcasts);
apiV1Routes.route('/', creators);
apiV1Routes.route('/', today);
apiV1Routes.route('/', editorialExperiments);
apiV1Routes.route('/', editorial);

export default apiV1Routes;
