import {
  BrandColors,
  Colors,
  CoolReadingScale,
  FilterChipPalette,
  OrangeScale,
  Radius,
  SemanticColorRoles,
  StatusColors,
} from '../foundations';

export type WebThemeVariables = Record<string, string>;

const FILTER_CHIP_FOREGROUNDS = {
  article: BrandColors.black,
  podcast: BrandColors.black,
  video: BrandColors.black,
  post: BrandColors.black,
} as const;

const WEB_THEME_EXTRAS = {
  '--shadow': '0 18px 40px rgba(0, 0, 0, 0.08)',
  '--frame-width': '70rem',
  '--font-sans': "'Inter Variable', Inter, system-ui, -apple-system, sans-serif",
  '--brand-black': BrandColors.black,
  '--brand-orange': BrandColors.orange,
  '--orange-50': OrangeScale[50],
  '--orange-100': OrangeScale[100],
  '--orange-300': OrangeScale[300],
  '--orange-500': OrangeScale[500],
  '--orange-700': OrangeScale[700],
  '--orange-950': OrangeScale[950],
  '--cool-reading-50': CoolReadingScale[50],
  '--cool-reading-100': CoolReadingScale[100],
  '--cool-reading-300': CoolReadingScale[300],
  '--cool-reading-500': CoolReadingScale[500],
  '--cool-reading-800': CoolReadingScale[800],
  '--cool-reading-950': CoolReadingScale[950],
  '--on-accent': SemanticColorRoles.light.onAccent,
  '--inline-link': SemanticColorRoles.light.inlineLink,
  '--dark-canvas': SemanticColorRoles.dark.canvas,
  '--dark-surface': SemanticColorRoles.dark.surface,
  '--dark-raised': SemanticColorRoles.dark.raised,
  '--dark-text': SemanticColorRoles.dark.primaryText,
  '--dark-text-secondary': SemanticColorRoles.dark.secondaryText,
  '--dark-border': SemanticColorRoles.dark.border,
  '--dark-inline-link': SemanticColorRoles.dark.inlineLink,
  '--status-success': StatusColors.success.accent,
  '--status-warning': StatusColors.warning.accent,
  '--status-danger': StatusColors.danger.accent,
  '--status-information': StatusColors.information.accent,
  '--workbench-paper': SemanticColorRoles.light.canvas,
  '--workbench-paper-deep': SemanticColorRoles.light.raised,
  '--workbench-sheet': SemanticColorRoles.light.surface,
  '--workbench-ink': SemanticColorRoles.light.primaryText,
  '--workbench-muted': SemanticColorRoles.light.secondaryText,
  '--workbench-line': SemanticColorRoles.light.border,
  '--workbench-accent': SemanticColorRoles.light.brandAccent,
  '--workbench-accent-soft': OrangeScale[100],
  '--workbench-success': StatusColors.success.accent,
  '--workbench-danger': StatusColors.danger.accent,
  '--workbench-sidebar': BrandColors.black,
  '--workbench-sidebar-raised': CoolReadingScale[800],
  '--workbench-sidebar-text': SemanticColorRoles.dark.secondaryText,
  '--workbench-sidebar-text-active': SemanticColorRoles.dark.primaryText,
} as const;

export function createWebThemeVariables(): WebThemeVariables {
  const colors = Colors.light;

  return {
    '--background': colors.surfaceCanvas,
    '--foreground': colors.textPrimary,
    '--card': colors.surfaceElevated,
    '--card-foreground': colors.textPrimary,
    '--popover': colors.surfaceElevated,
    '--popover-foreground': colors.textPrimary,
    '--primary': colors.accent,
    '--primary-foreground': colors.accentForeground,
    '--secondary': colors.surfaceSubtle,
    '--secondary-foreground': colors.textPrimary,
    '--muted': colors.surfaceSubtle,
    '--muted-foreground': colors.textSecondary,
    '--accent': colors.accent,
    '--accent-foreground': colors.accentForeground,
    '--destructive': colors.statusError,
    '--destructive-foreground': colors.overlayForeground,
    '--border': colors.borderDefault,
    '--input': colors.borderDefault,
    '--ring': 'rgba(239, 102, 31, 0.42)',
    '--radius': `${Radius.lg / 16}rem`,
    '--surface-canvas': colors.surfaceCanvas,
    '--surface-subtle': colors.surfaceSubtle,
    '--surface-elevated': colors.surfaceElevated,
    '--surface-raised': colors.surfaceRaised,
    '--line': colors.borderSubtle,
    '--line-strong': colors.borderDefault,
    '--text': colors.textPrimary,
    '--text-subheader': colors.textSubheader,
    '--text-dim': colors.textSecondary,
    '--text-tertiary': CoolReadingScale[500],
    '--danger': StatusColors.danger.accent,
    '--success': StatusColors.success.accent,
    '--warning': StatusColors.warning.accent,
    '--info': StatusColors.information.accent,
    '--status-success-surface': colors.statusSuccessSurface,
    '--status-warning-surface': colors.statusWarningSurface,
    '--status-error-surface': colors.statusErrorSurface,
    '--status-info-surface': colors.statusInfoSurface,
    '--filter-chip-article-accent': FilterChipPalette.article.accent,
    '--filter-chip-article-foreground': FILTER_CHIP_FOREGROUNDS.article,
    '--filter-chip-article-surface': FilterChipPalette.article.surface,
    '--filter-chip-podcast-accent': FilterChipPalette.podcast.accent,
    '--filter-chip-podcast-foreground': FILTER_CHIP_FOREGROUNDS.podcast,
    '--filter-chip-podcast-surface': FilterChipPalette.podcast.surface,
    '--filter-chip-video-accent': FilterChipPalette.video.accent,
    '--filter-chip-video-foreground': FILTER_CHIP_FOREGROUNDS.video,
    '--filter-chip-video-surface': FilterChipPalette.video.surface,
    '--filter-chip-post-accent': FilterChipPalette.post.accent,
    '--filter-chip-post-foreground': FILTER_CHIP_FOREGROUNDS.post,
    '--filter-chip-post-surface': FilterChipPalette.post.surface,
    ...WEB_THEME_EXTRAS,
  };
}

export function serializeCssVariables(selector: string, variables: WebThemeVariables): string {
  const lines = Object.entries(variables).map(([name, value]) => `  ${name}: ${value};`);
  return `${selector} {\n${lines.join('\n')}\n}`;
}
