/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SaveRouteImport } from './routes/save'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ApiDebuggerRouteImport } from './routes/debugger'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions/index'
import { Route as FeedSubscriptionIdRouteImport } from './routes/feed/$subscriptionId'
import { Route as SubscriptionsDiscoverProviderRouteImport } from './routes/subscriptions/discover/$provider'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveRoute = SaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebuggerRoute = ApiDebuggerRouteImport.update({
  id: '/debugger',
  path: '/debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSubscriptionIdRoute = FeedSubscriptionIdRouteImport.update({
  id: '/$subscriptionId',
  path: '/$subscriptionId',
  getParentRoute: () => FeedRoute,
} as any)
const SubscriptionsDiscoverProviderRoute =
  SubscriptionsDiscoverProviderRouteImport.update({
    id: '/subscriptions/discover/$provider',
    path: '/subscriptions/discover/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/api-debugger': typeof ApiDebuggerRoute
  '/bookmarks': typeof BookmarksRoute
  '/feed': typeof FeedRouteWithChildren
  '/profile': typeof ProfileRoute
  '/save': typeof SaveRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/feed/$subscriptionId': typeof FeedSubscriptionIdRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
  '/subscriptions/discover/$provider': typeof SubscriptionsDiscoverProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/api-debugger': typeof ApiDebuggerRoute
  '/bookmarks': typeof BookmarksRoute
  '/feed': typeof FeedRouteWithChildren
  '/profile': typeof ProfileRoute
  '/save': typeof SaveRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/feed/$subscriptionId': typeof FeedSubscriptionIdRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
  '/subscriptions/discover/$provider': typeof SubscriptionsDiscoverProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/api-debugger': typeof ApiDebuggerRoute
  '/bookmarks': typeof BookmarksRoute
  '/feed': typeof FeedRouteWithChildren
  '/profile': typeof ProfileRoute
  '/save': typeof SaveRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/feed/$subscriptionId': typeof FeedSubscriptionIdRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
  '/subscriptions/discover/$provider': typeof SubscriptionsDiscoverProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/api-debugger'
    | '/bookmarks'
    | '/feed'
    | '/profile'
    | '/save'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/feed/$subscriptionId'
    | '/subscriptions'
    | '/subscriptions/discover/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/api-debugger'
    | '/bookmarks'
    | '/feed'
    | '/profile'
    | '/save'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/feed/$subscriptionId'
    | '/subscriptions'
    | '/subscriptions/discover/$provider'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/api-debugger'
    | '/bookmarks'
    | '/feed'
    | '/profile'
    | '/save'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/feed/$subscriptionId'
    | '/subscriptions/'
    | '/subscriptions/discover/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ApiDebuggerRoute: typeof ApiDebuggerRoute
  BookmarksRoute: typeof BookmarksRoute
  FeedRoute: typeof FeedRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SaveRoute: typeof SaveRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
  SubscriptionsDiscoverProviderRoute: typeof SubscriptionsDiscoverProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/save': {
      id: '/save'
      path: '/save'
      fullPath: '/save'
      preLoaderRoute: typeof SaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-debugger': {
      id: '/api-debugger'
      path: '/api-debugger'
      fullPath: '/api-debugger'
      preLoaderRoute: typeof ApiDebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$subscriptionId': {
      id: '/feed/$subscriptionId'
      path: '/$subscriptionId'
      fullPath: '/feed/$subscriptionId'
      preLoaderRoute: typeof FeedSubscriptionIdRouteImport
      parentRoute: typeof FeedRoute
    }
    '/subscriptions/discover/$provider': {
      id: '/subscriptions/discover/$provider'
      path: '/subscriptions/discover/$provider'
      fullPath: '/subscriptions/discover/$provider'
      preLoaderRoute: typeof SubscriptionsDiscoverProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FeedRouteChildren {
  FeedSubscriptionIdRoute: typeof FeedSubscriptionIdRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedSubscriptionIdRoute: FeedSubscriptionIdRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ApiDebuggerRoute: ApiDebuggerRoute,
  BookmarksRoute: BookmarksRoute,
  FeedRoute: FeedRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SaveRoute: SaveRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
  SubscriptionsDiscoverProviderRoute: SubscriptionsDiscoverProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
