name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
    # paths:
    #   - 'packages/api/**'
    #   - 'packages/shared/**'
    #   - 'apps/web/**'
    #   - 'package.json'
    #   - 'bun.lockb'
    #   - '.github/workflows/deploy.yml'
  pull_request:
    branches: [main]
    # paths:
    #   - 'packages/api/**'
    #   - 'packages/shared/**'
    #   - 'apps/web/**'
    #   - 'package.json'
    #   - 'bun.lockb'
    #   - '.github/workflows/deploy.yml'

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    name: Deploy API
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Type check
        run: bun run type-check
        working-directory: packages/api
        
      - name: Build shared package
        run: bun run build
        working-directory: packages/shared
        
      - name: Build API
        run: bun run build
        working-directory: packages/api
        
      - name: Run database migrations (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: packages/api
          command: d1 migrations apply --env production --remote DB
          
      - name: Set Clerk Secret (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "${{ secrets.CLERK_SECRET_KEY_PRODUCTION }}" | bunx wrangler secret put CLERK_SECRET_KEY --env production
        working-directory: packages/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: packages/api
          command: deploy --env production
          
      - name: Purge Cache (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
          
      - name: Set Clerk Secret (Preview)
        if: github.event_name == 'pull_request'
        run: echo "${{ secrets.CLERK_SECRET_KEY_DEV }}" | bunx wrangler secret put CLERK_SECRET_KEY --name zine-api-$(echo "${{ github.head_ref }}" | sed 's|[^a-zA-Z0-9-]|-|g')
        working-directory: packages/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: packages/api
          command: deploy --name zine-api-$(echo "${{ github.head_ref }}" | sed 's|[^a-zA-Z0-9-]|-|g')
        id: preview_deploy
        
      - name: Comment Preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const sanitizedBranch = "${{ github.head_ref }}".replace(/[^a-zA-Z0-9-]/g, '-');
            const deploymentUrl = `https://zine-api-${sanitizedBranch}.${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.workers.dev`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **API Preview Deployment Ready!**
              
              **Preview URL:** ${deploymentUrl}
              **Branch:** \`${{ github.head_ref }}\`
              **Commit:** \`${{ github.sha }}\`
              
              Test your API endpoints at: ${deploymentUrl}/api/v1/`
            })
            
  deploy-web:
    runs-on: ubuntu-latest
    name: Deploy Web App
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Type check
        run: bun run type-check
        working-directory: apps/web
        
      - name: Build shared package
        run: bun run build
        working-directory: packages/shared
        
      - name: Build Web App (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY" > .env.production
          echo "Building with environment variables..."
          cat .env.production
          bunx dotenv-cli -e .env.production -- bun run build
          # Replace BUILD_TIME placeholder in wrangler.toml
          BUILD_TIME=$(date -u +%Y%m%d%H%M%S)
          sed -i "s/{{BUILD_TIME}}/$BUILD_TIME/g" wrangler.toml
        working-directory: apps/web
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY_PRODUCTION }}
          
      - name: Build Web App (Preview)
        if: github.event_name == 'pull_request'
        run: bun run build
        working-directory: apps/web
        env:
          VITE_CLERK_PUBLISHABLE_KEY_DEV: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY_DEV }}
        
      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/web
          command: deploy --env production
          
      - name: Purge Cache (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
          
      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/web
          command: deploy --name zine-web-$(echo "${{ github.head_ref }}" | sed 's|[^a-zA-Z0-9-]|-|g')
        id: web_preview_deploy
        
      - name: Comment Preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const sanitizedBranch = "${{ github.head_ref }}".replace(/[^a-zA-Z0-9-]/g, '-');
            const deploymentUrl = `https://zine-web-${sanitizedBranch}.${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.workers.dev`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🌐 **Web App Preview Deployment Ready!**
              
              **Preview URL:** ${deploymentUrl}
              **Branch:** \`${{ github.head_ref }}\`
              **Commit:** \`${{ github.sha }}\`
              
              View your web app at: ${deploymentUrl}`
            })